routes/web.php
<?php

use App\Http\Controllers\GameController;
use App\Http\Controllers\GeneralStatisticsController;
use App\Http\Controllers\GoalController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PlayerController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => true]);

Route::group(['middleware' => 'auth'], function () {

    Route::get('/home', [HomeController::class, 'index'])->name('home');

    Route::resource('user', UserController::class);
    Route::resource('player', PlayerController::class);
    Route::resource('game', GameController::class);
    Route::post('/game/processNewGoal', [GameController::class, 'processNewGoal'])
        ->name('game.processNewGoal');
    Route::post('/game/redirectFromSetScoreScreen', [GameController::class, 'redirectFromSetScoreScreen'])
        ->name('game.redirectFromSetScoreScreen');
    Route::get('/game/{id}/displayStatistics', [GameController::class, 'displayStatistics'])
        ->name('game.displayStatistics');
    Route::get('/player/{id}/displayStatistics', [PlayerController::class, 'displayStatistics'])
        ->name('player.displayStatistics');
    Route::get('/game/{id}/goToSetScoreScreen', [GameController::class, 'goToSetScoreScreen'])
        ->name('game.goToSetScoreScreen');
    Route::resource('generalStatistics', GeneralStatisticsController::class);
    
   
    Route::resource('goal', GoalController::class);
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    public function game()
    {
        return $this->belongsTo(Game::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UserRequest;
use App\Models\User;
use Illuminate\Database\QueryException;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\DB;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $user = User::all();

        return view('users.index')->with('users', $user);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('users.createOrUpdate');
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  UserRequest  $request
     * @return Response
     */
    public function store(UserRequest $request)
    {
        try {
            User::create($request->all());
        } catch (QueryException $e) {
            $request->session()->flash('error', 'Gebruiker aanmaken mislukt');
            return redirect()->back();
        } catch (\Exception $e) {
            $request->session()->flash('error', 'Gebruiker aanmaken mislukt');
            return redirect()->back();
        }
        echo "test";
        return redirect()->route('user.index')
            ->with('success', 'Gebruiker aangemaakt!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show(int $id)
    {
        $user = User::findOrFail($id);
        return view('users.show')
            ->with('user', $user);
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  User $user
     * @return Response
     */
    public function edit(User $user)
    {
        return view('users.createOrUpdate')->with('user', $user);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  UserRequest  $request
     * @return Response
     */
    public function update(UserRequest $request)
    {
        try {
            $user = User::findOrFail($request->id);
            $user->update([
                'name' => $request->name,
                'email' => $request->email,
            ]);
        } catch (QueryException $e) {
            $request->session()->flash('error', 'Gebruiker bijwerken mislukt');
            return redirect()->back();
        } catch (\Exception $e) {
            $request->session()->flash('error', 'Gebruiker bijwerken mislukt');
            return redirect()->back();
        }
        $request->session()->flash('success', 'Gebruiker bijgewerkt');
        return redirect()->route('user.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  User $user
     * @return Response
     */
    public function destroy(User $user)
    {
        $user->delete();

        return redirect()->route('user.index')
            ->with('success', 'Gebruiker verwijderd!');
    }
}

resources/views/Users/createOrUpdate.blade.php
<!DOCTYPE html>
@extends('layouts.app')
@section('content')
    @if(isset($user))
        {{ Form::model($user, ['route' => ['user.update', $user->id], 'method' => 'put']) }}
        {{ Form::hidden('id', $user->id) }}
        @if (session ('error'))
        <div style="display: flex" class="alert alert-danger">
                <strong class="text-center">{{ session('error') }}</strong>
                <div style="display: flex; justify-content: right">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                </div>
            </div>
        @endif
    @else
        {{ Form::open(['route' => 'user.store', 'method' => 'post']) }}
        @if (session ('error'))
        <div style="display: flex" class="alert alert-danger">
                <strong class="text-center">{{ session('error') }}</strong>
                <div style="display: flex; justify-content: right">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                </div>
            </div>
        @endif
    @endif
        <label for="name">Naam:</label>
        {{ Form::text('name', Request::old('name')) }}
        @if ($errors->has('name'))
            <span class="text-danger">{{ $errors->first('name') }}</span>
        @endif
        <label for="email">E-mail:</label>
        {{ Form::email('email', Request::old('email')) }}
        @if ($errors->has('email'))
            <span class="text-danger">{{ $errors->first('email') }}</span> 
        @endif
        
    @if(!isset($user))
        <label for="password">Wachtwoord:</label>
        {{ Form::password('password', Request::old('password')) }}
        @if ($errors->has('password'))
            <span class="text-danger">{{ $errors->first('password') }}</span> 
        @endif
        
    @endif
        {{ Form::submit('Opslaan', ['class'=>'btn btn-primary', 'id' => 'save_button']) }}
        {{ Form::close() }}
@endsection

resources/views/Users/index.blade.php
@extends('layouts.app')
@section('content')
    <div>
        @if (session('success'))
            <div style="display: flex" class="alert alert-success">
                <strong class="text-center">{{ session('success') }}</strong>
                <div style="display: flex; justify-content: right">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                </div>
            </div>
        @endif
            <div style="padding-left: 3.5rem; height: 70px">
                <a href="{{ route('user.create') }}" ; class="btn btn-success btn-lg shadow-sm">Nieuwe gebruiker</a>
            </div>
        <div class="container">
            <div class="row">
                <div class="col col-lg-2">ID</div>
                <div class="col col-lg-2">NAAM</div>
                <div class="col col-lg-2">E-MAIL</div>
                <div class="col col-lg-2">ACTIE</div>
            </div>
            @foreach($users as $user)
                <div class="row">
                    <div class="col col-lg-2">{{ $user->id }}</div>
                    <div class="col col-lg-2"><a href="{{ route('user.show', $user->id) }}" ; class="nav-link">{{ $user->name }}</div>
                    <div class="col col-lg-2"><a href="mailto:{{ $user->email }}">{{ $user->email }}</a></div>
                    <div class="row">
                        <form action="{{ route('user.destroy', $user->id) }}" method="POST" onsubmit="return confirm('Weet je het zeker?')">
                            <a class="btn btn-outline-secondary" href="{{ route('user.edit', $user->id) }}">Bewerken</a>
                            @csrf
                            @method('DELETE')
                            <button name="btn" id="delete_button" type="submit" class="btn btn-outline-danger">Verwijder</button>
                        </form>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
@endsection

resources/views/Users/show.blade.php
@extends('layouts.app')
@section('content')
    <div style="text-align: center;">
        <h1 class="shadow-sm p-3 mb-5 bg-white rounded">Weergave gebruiker</h1>
    </div>
    <div style="display: flex; justify-content: center;">
        <div class="card text-center shadow p-3 mb-5 bg-white rounded" style="display: inline-flex; width: 30rem">
            <img class="card-img-top" src="" alt="Profiel foto">
            <div class="card-body" style="height: 20rem;">
                <h1 style="font-size: 35px;" class="card-title">{{ $user->name }}</h1>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">E-mailadres: &nbsp;<a href="mailto:{{ $user->email }}">{{ $user->email }}</a></li>
                <li class="list-group-item">Admin status: &nbsp; {{ $user->is_admin }}</li>
                <li class="list-group-item"></li>
            </ul>
            <div class="card-body" style="display: flex; justify-content: center;">
                <a href="{{ route('user.index') }}" class="btn btn-primary btn-lg">Terug</a>
            </div>
        </div>
    </div>
@endsection