routes/web.php
<?php

use App\Http\Controllers\GameController;
use App\Http\Controllers\GeneralStatisticsController;
use App\Http\Controllers\GoalController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PlayerController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => true]);

Route::group(['middleware' => 'auth'], function () {

    Route::get('/home', [HomeController::class, 'index'])->name('home');

    Route::resource('user', UserController::class);
    Route::resource('player', PlayerController::class);
    Route::resource('game', GameController::class);
    Route::post('/game/processNewGoal', [GameController::class, 'processNewGoal'])
        ->name('game.processNewGoal');
    Route::post('/game/redirectFromSetScoreScreen', [GameController::class, 'redirectFromSetScoreScreen'])
        ->name('game.redirectFromSetScoreScreen');
    Route::get('/game/{id}/displayStatistics', [GameController::class, 'displayStatistics'])
        ->name('game.displayStatistics');
    Route::get('/player/{id}/displayStatistics', [PlayerController::class, 'displayStatistics'])
        ->name('player.displayStatistics');
    Route::get('/game/{id}/goToSetScoreScreen', [GameController::class, 'goToSetScoreScreen'])
        ->name('game.goToSetScoreScreen');
    Route::resource('generalStatistics', GeneralStatisticsController::class);
    
   
    Route::resource('goal', GoalController::class);
});

app/Http/Controllers/GameController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\GameRequest;
use App\Models\Game;
use App\Models\Goal;
use App\Models\Player;
use App\Models\User;
use Auth;
use DB;
use Doctrine\DBAL\Query\QueryException;
use Exception;
use Illuminate\Contracts\View\View;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;

class GameController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return View
     */
    public function index(): View
    {
        $games = Game::all();
        
        return view('Games.index')
            ->with('games', $games);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return View
     */
    public function create(): View
    {
        $players = Player::all();
        return view('Games.createOrUpdate')
            ->with('players', $players);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  GameRequest  $request
     * @return RedirectResponse
     */
    public function store(GameRequest $request): RedirectResponse
    {
        try {
            $game = new Game();
            $game->team_one_attack_player_one_id = $request->team_one_attack_player_one_id;
            $game->team_one_defend_player_two_id = $request->team_one_defend_player_two_id;
            $game->team_two_attack_player_three_id = $request->team_two_attack_player_three_id;
            $game->team_two_defend_player_four_id = $request->team_two_defend_player_four_id;
            $game->user_id = Auth::user()->id;
            $game->save();
        } catch (QueryException $e) {
            session()->flash('error', 'Wedstrijd aanmaken mislukt');
            return redirect()->back();
        } catch (Exception $e) {
            session()->flash('error', 'Wedstrijd aanmaken mislukt');
            return redirect()->back();
        }
        return redirect()
            ->route('game.index')
            ->with('success', 'Wedstrijd aangemaakt!');
    }

    /**
     * Display the specified resource.
     *
     * @param  Game  $game
     * @return View
     */
    public function show(Game $game): View
    {
        $gameData = [
            'players' =>
            $game->teamOneAttackPlayerOneId->fullname . ', ' .
            $game->teamOneAttackPlayerOneId->fullname . ', ' .
            $game->teamOneDefendPlayerTwoId->fullname . ', ' .
            $game->teamTwoAttackPlayerThreeId->fullname . ', ' .
            $game->teamTwoDefendPlayerFourId->fullname . ', ' ,
            'createdBy' => $game->user_id,
            'dateOfCreation' => $game->dateOfGame(),
            'totalGameDuration' => $game->calculateGameDuration()->format("%I:%S"),
        ];

        return view('Games.show')
            ->with('game', $game)
            ->with('gameData', $gameData);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  game  $game
     * @return View
     */
    public function edit(Game $game): View
    {
        $players = Player::all();
        return view('Games.createOrUpdate')
            ->with('game', $game)
            ->with('players', $players);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Game  $game
     * @param  GameRequest  $request
     * @return RedirectResponse
     */
    public function update(GameRequest $request, Game $game): RedirectResponse
    {
        try {
            $game->team_one_attack_player_one_id = $request['team_one_attack_player_one_id'];
            $game->team_one_defend_player_two_id = $request['team_one_defend_player_two_id'];
            $game->team_two_attack_player_three_id = $request['team_two_attack_player_three_id'];
            $game->team_two_defend_player_four_id = $request['team_two_defend_player_four_id'];
            $game->user_id = Auth::user()->id;
            $game->save();
        } catch (QueryException $e) {
            session()->flash('error', 'Wedstrijd bijwerken mislukt');
            return redirect()->back();
        } catch (Exception $e) {
            session()->flash('error', 'Wedstrijd bijwerken mislukt');
            return redirect()->back();
        }

        session()->flash('success', 'Wedstrijd bijgewerkt');

        return redirect()
            ->route('game.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Game  $game
     * @return Response
     */
    public function destroy(Game $game): RedirectResponse
    {
        $game->delete();
        session()->flash('success', 'Wedstrijd verwijderd!');
        return redirect()
            ->route('game.index');
    }

    public function processNewGoal(Request $request)
    {
        $game = Game::findOrFail($request->game_id);

        $newGoal = new Goal();
        $newGoal->game_id = $game->id;
        $newGoal->player_id = $request->player_id;
        $newGoal->own_goal = $request->boolean('own_goal');
        $newGoal->midfield_goal = $request->boolean('midfield_goal');
        $newGoal->save();
        
        $game->calculateNewGoal($newGoal);
        $game->save();
        return $game->toJson();
    }

    public function redirectFromSetScoreScreen(): RedirectResponse
    {
        session()->flash('success', 'Score toegevoegd!');
        return redirect()
            ->route('game.index');
    }
    
    public function displayStatistics(Request $request): View
    {
        $game = Game::findOrFail($request->route('id'));
        $players = [
            $game->teamOneAttackPlayerOneId,
            $game->teamOneDefendPlayerTwoId,
            $game->teamTwoAttackPlayerThreeId,
            $game->teamTwoDefendPlayerFourId,
        ];
        
        $score = $game->team_one_total_score . ' - ' . $game->team_two_total_score;

        return view('Games.statistics')
            ->with('score', $score)
            ->with('statisticsTeamOne', $game->statisticsTeamOne())
            ->with('statisticsTeamTwo', $game->statisticsTeamTwo())
            ->with('goalStats', $game->getStatistics())
            ->with('totalGameDuration', $game->calculateGameDuration()->format("%I:%S"))
            ->with('dateOfGame', $game->dateOfGame())
            ->with('generalStats', $game->generalGameStats())
            ->with('game', $game)
            ->with('players', $players);
    }

    public function goToSetScoreScreen(int $id): View
    {
        $game = Game::findOrFail($id);

        return view('Games.setScoreScreen')
            ->with('game', $game);
    }
}

resources/views/Games/createOrUpdate.blade.php
@extends('layouts.app')
@section('content')
    @if (session ('error'))
        <div style="display: flex" class="alert alert-danger">
            <strong class="text-center">{{ session('error') }}</strong>
            <div style="display: flex; justify-content: right">
                <button type="button" class="close" data-dismiss="alert">×</button>
            </div>
        </div>
    @endif
    @if(isset($game))
        {{ Form::model($game, ['route' => ['game.update', $game->id], 'method' => 'put']) }}
        {{ Form::hidden('id', $game->id) }}
    @else
        {{ Form::open(['route' => 'game.store', 'method' => 'post', 'id' => 'createGameForm']) }}
    @endif
            <script type="text/javascript">
                $(document).ready(function () {
                    var prevValuePlayerOne = false;
                    var prevValuePlayerTwo = false;
                    var prevValuePlayerThree= false;
                    var prevValuePlayerFour = false;

                    $("#team_one_attack_player_one_id").change(function () {
                        var dropdownPlayerOneSelectedOptionVal = $("#team_one_attack_player_one_id option:selected").val()
                        if (prevValuePlayerOne) {
                            $("#team_one_defend_player_two_id option[value='"+prevValuePlayerOne+"']").show();
                            $("#team_two_attack_player_three_id option[value='"+prevValuePlayerOne+"']").show();
                            $("#team_two_defend_player_four_id option[value='"+prevValuePlayerOne+"']").show();
                        }
                        $("#team_one_defend_player_two_id option[value='"+dropdownPlayerOneSelectedOptionVal+"']").hide();
                        $("#team_two_attack_player_three_id option[value='"+dropdownPlayerOneSelectedOptionVal+"']").hide();
                        $("#team_two_defend_player_four_id option[value='"+dropdownPlayerOneSelectedOptionVal+"']").hide();

                        prevValuePlayerOne = dropdownPlayerOneSelectedOptionVal;
                    });
                    $("#team_one_defend_player_two_id").change(function () {
                        var dropdownPlayerTwoSelectedOptionVal = $("#team_one_defend_player_two_id option:selected").val()
                        if (prevValuePlayerTwo) {
                            $("#team_one_attack_player_one_id option[value='"+prevValuePlayerTwo+"']").show();
                            $("#team_two_attack_player_three_id option[value='"+prevValuePlayerTwo+"']").show();
                            $("#team_two_defend_player_four_id option[value='"+prevValuePlayerTwo+"']").show();
                        }
                        $("#team_one_attack_player_one_id option[value='"+dropdownPlayerTwoSelectedOptionVal+"']").hide();
                        $("#team_two_attack_player_three_id option[value='"+dropdownPlayerTwoSelectedOptionVal+"']").hide();
                        $("#team_two_defend_player_four_id option[value='"+dropdownPlayerTwoSelectedOptionVal+"']").hide();

                        prevValuePlayerTwo = dropdownPlayerTwoSelectedOptionVal;
                    });
                    $("#team_two_attack_player_three_id").change(function () {
                        var dropdownPlayerThreeSelectedOptionVal = $("#team_two_attack_player_three_id option:selected").val()
                        if (prevValuePlayerThree) {
                            $("#team_one_attack_player_one_id option[value='"+prevValuePlayerThree+"']").show();
                            $("#team_one_defend_player_two_id option[value='"+prevValuePlayerThree+"']").show();
                            $("#team_two_defend_player_four_id option[value='"+prevValuePlayerThree+"']").show();
                        }
                        $("#team_one_attack_player_one_id option[value='"+dropdownPlayerThreeSelectedOptionVal+"']").hide();
                        $("#team_one_defend_player_two_id option[value='"+dropdownPlayerThreeSelectedOptionVal+"']").hide();
                        $("#team_two_defend_player_four_id option[value='"+dropdownPlayerThreeSelectedOptionVal+"']").hide();

                        prevValuePlayerThree = dropdownPlayerThreeSelectedOptionVal;
                    });
                    $("#team_two_defend_player_four_id").change(function () {
                        var dropdownPlayerFourSelectedOptionVal = $("#team_two_defend_player_four_id option:selected").val()
                        if (prevValuePlayerFour) {
                            $("#team_one_attack_player_one_id option[value='"+prevValuePlayerFour+"']").show();
                            $("#team_one_defend_player_two_id option[value='"+prevValuePlayerFour+"']").show();
                            $("#team_two_attack_player_three_id option[value='"+prevValuePlayerFour+"']").show();
                        }
                        $("#team_one_attack_player_one_id option[value='"+dropdownPlayerFourSelectedOptionVal+"']").hide();
                        $("#team_one_defend_player_two_id option[value='"+dropdownPlayerFourSelectedOptionVal+"']").hide();
                        $("#team_two_attack_player_three_id option[value='"+dropdownPlayerFourSelectedOptionVal+"']").hide();
                        
                        prevValuePlayerFour = dropdownPlayerFourSelectedOptionVal;
                    });
                });
            </script>
            <h1>Team 1</h1>
            {{ Form::label('team_one_attack_player_one_id', 'Speler 1 (aanvallend)') }}
            {{ Form::select('team_one_attack_player_one_id', $players->pluck('fullname', 'id'), Request::old('team_one_attack_player_one_id'), ['class' => 'form-control', 'placeholder' => 'Selecteer speler 1']) }}
            @error('team_one_attack_player_one_id')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            {{ Form::label('team_one_defend_player_two_id', 'Speler 2 (verdedigend)')}}
            {{ Form::select('team_one_defend_player_two_id', $players->pluck('fullname', 'id'), Request::old('team_one_defend_player_two_id'), ['class' => 'form-control', 'placeholder' => 'Selecteer speler 2']) }}
            @error('team_one_defend_player_two_id')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            <h1>Team 2</h1>
            {{ Form::label('team_two_attack_player_three_id', 'Speler 3 (aanvallend)')}}
            {{ Form::select('team_two_attack_player_three_id', $players->pluck('fullname', 'id'), Request::old('team_two_attack_player_three_id'), ['class' => 'form-control', 'placeholder' => 'Selecteer speler 3']) }}
            @error('team_two_attack_player_three_id')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            {{ Form::label('team_two_defend_player_four_id', 'Speler 4 (verdedigend)')}}
            {{ Form::select('team_two_defend_player_four_id', $players->pluck('fullname', 'id'), Request::old('team_two_defend_player_four_id'), ['class' => 'form-control', 'placeholder' => 'Selecteer speler 4']) }}
            @error('team_two_defend_player_four_id')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            {{ Form::submit('Opslaan', ['class'=>'btn btn-primary', 'id' => 'save_button']) }}
        {{ Form::close() }}
@endsection

resources/views/Games/index.blade.php
@extends('layouts.app')
@section('content')
    <div>
        @if (session('success'))
            <div style="display: flex" class="alert alert-success">
                <strong class="text-center">{{ session('success') }}</strong>
                <div style="display: flex; justify-content: right">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                </div>
            </div>
        @endif
        <div style="padding-left: 3.5rem; height: 70px">
            <a href="{{ route('game.create')}}" ; class="btn btn-success btn-lg shadow-sm">Nieuwe wedstrijd</a>
        </div>
        <div class="container">
            <div class="row">
                <div class="col col-lg-2 font-weight-bold">Wedstrijd</div>
                <div class="col col-lg-2 font-weight-bold">Aangemaakt door</div>
                <div class="col col-lg-2 font-weight-bold">Team 1</div>
                <div class="col col-lg-2 font-weight-bold">Team 2</div>
                <div class="col col-lg-2 font-weight-bold">Score</div>
            </div>
            @foreach($games as $game)
                <div class="row">
                    <div class="col col-lg-2">
                        <a href="{{ route('game.show', $game->id) }}">{{ $game->id }}</a>
                    </div>
                    <div class="col col-lg-2">{{ $game->user->name }}</div>
                    <div class="col col-lg-2">
                        {{ $game->teamOneAttackPlayerOneId->fullname ?? 'onbekend'}},
                        {{ $game->teamOneDefendPlayerTwoId->fullname ?? 'onbekend'}}
                    </div>
                    <div class="col col-lg-2">
                        {{ $game->teamTwoAttackPlayerThreeId->fullname ?? 'onbekend'}},
                        {{ $game->teamTwoDefendPlayerFourId->fullname ?? 'onbekend'}}
                    </div>
                    <div class="col col-lg-2">
                        <span> {{ $game->team_one_total_score . ' - ' . $game->team_two_total_score}} </span>
                    </div>
                    <div class="col">
                        <div class="row">
                            <a class="btn btn-outline-info" href="{{ route('game.displayStatistics', $game->id) }}">Info</a>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
@endsection

resources/views/Games/setScoreScreen.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
            <div class="row justify-content-md-center">
                <div class="h1">Wedstrijd {{ $game->id }}</div>
            </div>
@include('Games.setScore')
@endsection

resources/views/Games/show.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="col">
        <div class="row justify-content-md-center">
            <div class="h1">{{ $game->id }}</div>
        </div>
        <div class="row justify-content-md-center">
            <a class="btn btn-warning" href="{{ route('game.goToSetScoreScreen', $game->id) }}">Score zetten</a>
        </div>
        <div class="row justify-content-md-center h2">Info</div>
    </div>
    <div class="col">
        <div class="row">
            <ul class="list-group">
                <li class="list-group-item">Spelers: {{ $gameData['players'] }} </li>
                <li class="list-group-item">Aangemaakt door: {{ $gameData['createdBy'] }}</li>
                <li class="list-group-item">Aangemaakt: {{ $gameData['dateOfCreation'] }}</li>
                <li class="list-group-item">Duur: {{ $gameData['totalGameDuration'] }}</li>
            </ul>
        </div>
        <div class="row">
            <a class="btn btn-outline-secondary" href="{{ route('game.edit', $game->id) }}">Bewerken</a>
            {{ Form::open(['route'=> ['game.destroy', $game->id], 'onsubmit'=> "return confirm('Weet je het zeker?')", 'method'=>'POST']) }}
            {{ method_field('DELETE') }}
            {{ Form::submit('Verwijderen', ['class'=>'btn btn-outline-danger', 'id' => 'delete_button'])}}
            {{ Form::close()}}
        </div>
    </div>
</div>
@endsection

resources/views/Games/statistics.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-md-center">
        <div class="h1">Game {{ $game->id }}</div>
    </div>
    <div class="row justify-content-md-center">
        <div class="col; h6">{{ $totalGameDuration }}</div>
        <div class="row justify-content-md-center">
            <div class="col; h5">
                <div class="row">A: {{ $game->teamOneAttackPlayerOneId->fullname ?? 'Niet gevonden'}}</div>
                <div class="row">V: {{ $game->teamOneDefendPlayerTwoId->fullname }}</div>
            </div>
            <div class="col col-lg-2; h2">{{ $score }}</div>
            <div class="col; h5">
                <div class="row">A: {{ $game->teamTwoAttackPlayerThreeId->fullname ?? 'Niet gevonden'}}</div>
                <div class="row">V: {{ $game->teamTwoDefendPlayerFourId->fullname ?? 'Niet gevonden'}}</div>
            </div>
        </div>
        <div class="col; h6">{{ $dateOfGame }}</div>
    </div>
    <div class="row">
        <div class="row justify-content-md-center">
            <div class="h1">Spelers</div>
        </div>
        @foreach ($players as $player)
        <div class="col-sm">
            <div> {{ $player->fullname }} </div>
            <div class="card" style="width: 14rem;">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Goals: {{ count($goalStats[$player->id]['goal']) ?? '0' }} </li>
                    <li class="list-group-item">Eigen goal: {{ count($goalStats[$player->id]['ownGoal']) ?? '0' }} </li>
                    <li class="list-group-item">Middenveld goal: {{ count($goalStats[$player->id]['midfieldGoal']) ?? '0' }}</li>
                </ul>
            </div>
        </div>
        @endforeach
        <div class="row justify-content-md-center">
            <div class="row">
                <div class="h1">Algemeen</div>
                <div class="card" style="width: 14rem;">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">Totaal goals: {{ count($generalStats['totalGoals']) ?? '0' }} </li>
                        <li class="list-group-item">Totaal eigen goals: {{ count($generalStats['totalOwnGoals']) ?? '0' }}</li>
                        <li class="list-group-item">Totaal middenveld goals: {{ count($generalStats['totalMidfieldGoals']) ?? '0' }}</li>
                        
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div>
        <ol class="list-group list-group-flush">
            <div class="row">
                <div class="col">Team 1</div>
                <div class="col"></div>
                <div class="col">Team 2</div>
            </div>
            <div class="row">
                <div class="col">{{ count($statisticsTeamOne['ownGoals']) ?? '0' }}</div>
                <div class="col">
                    Eigen goals
                    <div class="row">
                        <div class="col">
                            <div class="progress">
                                <div class="progress-bar w-75" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
                            </div>
                        </div>
                        <div class="col">
                            <div class="progress">
                                <div class="progress-bar w-75" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col">{{ count($statisticsTeamTwo['ownGoals']) ?? '0' }}</div>
            </div>
            <div class="row">
                <div class="col">{{ count($statisticsTeamOne['midfieldGoals']) ?? '0' }}</div>
                <div class="col">
                    Middenveld goals
                    <div class="row">
                        <div class="col">
                            <div class="progress">
                                <div class="progress-bar w-75" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
                            </div>
                        </div>
                        <div class="col">
                            <div class="progress">
                                <div class="progress-bar w-75" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col">{{ count($statisticsTeamTwo['midfieldGoals']) ?? '0' }}</div>
            </div>
            <div class="row">
                <div class="col">...</div>
                <div class="col">
                    Gemmidelde tijd per goal
                    <div class="row">
                        <div class="col">
                            <div class="progress">
                                <div class="progress-bar w-75" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
                            </div>
                        </div>
                        <div class="col">
                            <div class="progress">
                                <div class="progress-bar w-75" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col">...</div>
            </div>
            <div class="row">
                <div class="col">{{ $statisticsTeamOne['winChance'][0] ?? '0' }} %</div>
                <div class="col">
                    Winkans %
                    <div class="row">
                        <div class="col">
                            <div class="progress">
                                <div class="progress-bar w-75" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
                            </div>
                        </div>
                        <div class="col">
                            <div class="progress">
                                <div class="progress-bar w-75" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col">{{ $statisticsTeamTwo['winChance'][0] ?? '0' }} %</div>
            </div>
        </ol>
    </div>
</div>
@endsection