routes/web.php
<?php

use App\Http\Controllers\GameController;
use App\Http\Controllers\GeneralStatisticsController;
use App\Http\Controllers\GoalController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PlayerController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => true]);

Route::group(['middleware' => 'auth'], function () {

    Route::get('/home', [HomeController::class, 'index'])->name('home');

    Route::resource('user', UserController::class);
    Route::resource('player', PlayerController::class);
    Route::resource('game', GameController::class);
    Route::post('/game/processNewGoal', [GameController::class, 'processNewGoal'])
        ->name('game.processNewGoal');
    Route::post('/game/redirectFromSetScoreScreen', [GameController::class, 'redirectFromSetScoreScreen'])
        ->name('game.redirectFromSetScoreScreen');
    Route::get('/game/{id}/displayStatistics', [GameController::class, 'displayStatistics'])
        ->name('game.displayStatistics');
    Route::get('/player/{id}/displayStatistics', [PlayerController::class, 'displayStatistics'])
        ->name('player.displayStatistics');
    Route::get('/game/{id}/goToSetScoreScreen', [GameController::class, 'goToSetScoreScreen'])
        ->name('game.goToSetScoreScreen');
    Route::resource('generalStatistics', GeneralStatisticsController::class);
    
   
    Route::resource('goal', GoalController::class);
});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- CSRF Token -->
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <title>{{ config('app.name', 'Laravel') }}</title>
        <!-- Scripts -->
        <script src="{{ mix('/js/app.js') }}"></script>
        <!-- Fonts -->
        <link rel="dns-prefetch" href="//fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
        <!-- Styles -->
        <link href="{{ mix('css/app.css') }}" rel="stylesheet">
    </head>
    <body>
        <div id="app">
            <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
                <div class="container">
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                        <ul class="navbar-nav mr-auto">
                            <li>
                                <a class="dropdown-item" href="{{ route('user.index') }}">Gebruikers</a>
                            </li>
                            <li>
                                <a class="drowdown-item" href="{{ route('player.index') }}">Spelers</a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{{ route('game.index') }}">Wedstrijden</a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{{ route('goal.index') }}">Goals</a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{{ route('generalStatistics.index') }}">Statistieken</a>
                            </li>
                        </ul>
                        <!-- Right Side Of Navbar -->
                        <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                        @if (Route::has('login'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                        @endif
                        @if (Route::has('register'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                        document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>
                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                    @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                        </ul>
                    </div>
                </div>
            </nav>
            <main class="py-4">
                @yield('content')
            </main>
        </div>
        @include('layouts.parts.generalJqueryFunctions')
        @stack('javascript')
    </body>
</html>