routes/web.php
<?php

use App\Http\Controllers\GameController;
use App\Http\Controllers\GeneralStatisticsController;
use App\Http\Controllers\GoalController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PlayerController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => true]);

Route::group(['middleware' => 'auth'], function () {

    Route::get('/home', [HomeController::class, 'index'])->name('home');

    Route::resource('user', UserController::class);
    Route::resource('player', PlayerController::class);
    Route::resource('game', GameController::class);
    Route::post('/game/processNewGoal', [GameController::class, 'processNewGoal'])
        ->name('game.processNewGoal');
    Route::post('/game/redirectFromSetScoreScreen', [GameController::class, 'redirectFromSetScoreScreen'])
        ->name('game.redirectFromSetScoreScreen');
    Route::get('/game/{id}/displayStatistics', [GameController::class, 'displayStatistics'])
        ->name('game.displayStatistics');
    Route::get('/player/{id}/displayStatistics', [PlayerController::class, 'displayStatistics'])
        ->name('player.displayStatistics');
    Route::get('/game/{id}/goToSetScoreScreen', [GameController::class, 'goToSetScoreScreen'])
        ->name('game.goToSetScoreScreen');
    Route::resource('generalStatistics', GeneralStatisticsController::class);
    
   
    Route::resource('goal', GoalController::class);
});

app/Http/Controllers/PlayerController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PlayerRequest;
use App\Models\Player;
use Doctrine\DBAL\Query\QueryException;
use Exception;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;

class PlayerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index(): View
    {
        $player = Player::all();
        return view('players.index')->with('players', $player);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create(): View
    {
        return view('players.createOrUpdate');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  PlayerRequest  $request
     * @return Response
     */
    public function store(PlayerRequest $request): RedirectResponse
    {
        try {
            Player::create($request->all());
        } catch (QueryException $e) {
            $request->session()->flash('error', 'Gebruiker aanmaken mislukt');
            return redirect()->back();
        } catch (Exception $e) {
            $request->session()->flash('error', 'Gebruiker aanmaken mislukt');
            return redirect()->back();
        }
        return redirect()->route('player.index')
            ->with('success', 'Gebruiker aangemaakt!');
    }

    /**
     * Display the specified resource.
     *
     * @param  Player  $player
     * @return Response
     */
    public function show(Player $player): View
    {
        $dateOfCreation = Carbon::parse($player->created_at)->format("d-m-Y");

        $playerData = [
            'fullname' => $player->fullname,
            'dateOfBirth' => $player->date_of_birth,
            'dateOfCreation' => $dateOfCreation,
        ];

        return view('players.show')
        ->with('player', $player)
        ->with('playerData', $playerData);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Player  $player
     * @return Response
     */
    public function edit(Player $player): View
    {
        return view('players.createOrUpdate')
            ->with('player', $player);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  PlayerRequest  $request
     * @return Response
     */
    public function update(PlayerRequest $request): RedirectResponse
    {
        try {
            $player = Player::findOrFail($request->id);
            $player->update([
                'firstname' => $request->firstname,
                'surname' => $request->surname,
                'date_of_birth' => $request->date_of_birth,
            ]);
        } catch (QueryException $e) {
            $request->session()->flash('error', 'Gebruiker bijwerken mislukt');
            return redirect()->back();
        } catch (\Exception $e) {
            $request->session()->flash('error', 'Gebruiker bijwerken mislukt');
            return redirect()->back();
        }
        $request->session()->flash('success', 'Gebruiker bijgewerkt');
        return redirect()->route('player.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Player  $player
     * @return Response
     */
    public function destroy(Player $player): RedirectResponse
    {
        $player->delete();
        return redirect()->route('player.index')
            ->with('success', 'Gebruiker verwijderd!');
    }

    public function displayStatistics(Request $request): View
    {
        $player = Player::findOrFail($request->route('id'));
        
        if ($player->countTotalGoalsAttack() > 0 || $player->countTotalGoalsDefend() > 0 || $player->countTotalGamesAttack() > 0
         || $player->countTotalGamesDefend() > 0) {
            $avgGoalsPerGameTotal = round(($player->countTotalGoalsAttack() + $player->countTotalGoalsDefend())
            / ($player->countTotalGamesAttack() + $player->countTotalGamesDefend()), 2);
        } else {
             $avgGoalsPerGameTotal = 0;
        }

        if ($player->countTotalOwnGoalsAttack() > 0 || $player->countTotalOwnGoalsDefend() > 0 || $player->countTotalGamesAttack() > 0
        || $player->countTotalGamesDefend() > 0) {
            $avgOwnGoalsPerGameTotal = round(($player->countTotalOwnGoalsAttack() + $player->countTotalOwnGoalsDefend())
            / ($player->countTotalGamesAttack() + $player->countTotalGamesDefend()), 2);
        } else {
            $avgOwnGoalsPerGameTotal = 0;
        }

        if ($player->countTotalMidfieldGoalsAttack() > 0 || $player->countTotalGoalsAttack() > 0) {
            $avgMidfieldGoalsPerGameTotal = round($player->countTotalMidfieldGoalsAttack()
            / $player->countTotalGoalsAttack(), 2);
        } else {
            $avgMidfieldGoalsPerGameTotal = 0;
        }

        $playerStatsTotal = [
            'playerGamesTotal' => $player->countTotalGamesAttack() + $player->countTotalGamesDefend(),
            'playerGoalsTotal' => $player->countTotalGoalsAttack() + $player->countTotalGoalsDefend(),
            'playerOwnGoalsTotal' => $player->countTotalOwnGoalsAttack() + $player->countTotalOwnGoalsDefend(),
            'playerMidfieldGoalsTotal' => $player->countTotalMidfieldGoalsAttack(),
            'avgGoalsPerGameTotal' => $avgGoalsPerGameTotal,
            'avgOwnGoalsPerGameTotal' => $avgOwnGoalsPerGameTotal,
            'avgMidfieldGoalsPerGameTotal' => $avgMidfieldGoalsPerGameTotal,
            'winPercentageTotal' => $player->winPercentageTotal(),
            'gameAppearanceTotal' => $player->playerGameAppearanceTotal(),
        ];

        if ($player->countTotalGoalsAttack() > 0 || $player->countTotalGamesAttack() > 0) {
            $avgGoalsPerGameAttack = round($player->countTotalGoalsAttack() / $player->countTotalGamesAttack(), 2);
        } else {
            $avgGoalsPerGameAttack = 0;
        }

        if ($player->countTotalOwnGoalsAttack() > 0 || $player->countTotalGamesAttack() > 0) {
            $avgOwnGoalsPerGameAttack = round($player->countTotalOwnGoalsAttack() / $player->countTotalGamesAttack(), 2);
        } else {
            $avgOwnGoalsPerGameAttack = 0;
        }

        if ($player->countTotalMidfieldGoalsAttack() > 0 || $player->countTotalGamesAttack() > 0) {
            $avgMidfieldGoalsPerGameAttack = round($player->countTotalMidfieldGoalsAttack() / $player->countTotalGamesAttack(), 2);
        } else {
            $avgMidfieldGoalsPerGameAttack = 0;
        }

        $playerStatsAttack = [
            'playerGamesAttack' => $player->countTotalGamesAttack(),
            'playerGoalsAttack' => $player->countTotalGoalsAttack(),
            'playerOwnGoalsAttack' => $player->countTotalOwnGoalsAttack(),
            'playerMidfieldGoalsAttack' => $player->countTotalMidfieldGoalsAttack(),
            'avgGoalsPerGameAttack' => $avgGoalsPerGameAttack,
            'avgOwnGoalsPerGameAttack' => $avgOwnGoalsPerGameAttack,
            'avgMidfieldGoalsPerGameAttack' => $avgMidfieldGoalsPerGameAttack,
            'winPercentageAttack' => $player->winPercentageAttack(),
            'gameAppearanceAttack' => $player->playerGameAppearanceAttack(),
        ];

        if ($player->countTotalGoalsDefend() > 0 || $player->countTotalGamesDefend() > 0) {
            $avgGoalsPerGameDefend = round($player->countTotalGoalsDefend() / $player->countTotalGamesDefend(), 2);
        } else {
            $avgGoalsPerGameDefend = 0;
        }

        if ($player->countTotalOwnGoalsDefend() > 0 || $player->countTotalGamesDefend() > 0) {
            $avgOwnGoalsPerGameDefend = round($player->countTotalOwnGoalsDefend() / $player->countTotalGamesDefend(), 2);
        } else {
            $avgOwnGoalsPerGameDefend = 0;
        }

        $playerStatsDefend = [
            'playerGamesDefend' => $player->countTotalGamesDefend(),
            'playerGoalsDefend' => $player->countTotalGoalsDefend(),
            'playerOwnGoalsDefend' => $player->countTotalOwnGoalsDefend(),
            'avgGoalsPerGameDefend' => $avgGoalsPerGameDefend,
            'avgOwnGoalsPerGameDefend' => $avgOwnGoalsPerGameDefend,
            'winPercentageDefend' => $player->winPercentageDefend(),
            'gameAppearanceDefend' => $player->playerGameAppearanceDefend(),
        ];
        
        ;
        if ($player->recentGame() == !null) {
            $recentGameCreatedTime = Carbon::parse($player->recentGame()->created_at);
            $recentGameUpdatedTime = Carbon::parse($player->recentGame()->updated_at);
            $totalRecentGameDuration = $recentGameCreatedTime->diff($recentGameUpdatedTime)->format("%I:%S");
        } else {
            $totalRecentGameDuration = 0;
        }
        
        if ($player->recentGame() == !null) {
            $recentGameDate = Carbon::parse($player->recentGame()->created_at)->format("d:m:Y");
        } else {
            $recentGameDate = 0;
        }
        
        if ($player->recentGame() == !null) {
            $score = $player->recentGame()->team_one_total_score . ' - ' . $player->recentGame()->team_two_total_score;
        } else {
            $score = 0;
        }
        

        $recentGameData = [
            'recentGameDuration' => $totalRecentGameDuration,
            'recentGameDate' => $recentGameDate,
            'score' => $score,
        ];
        
        return view('Players.statistics')
            ->with('playerStatsTotal', $playerStatsTotal)
            ->with('playerStatsAttack', $playerStatsAttack)
            ->with('playerStatsDefend', $playerStatsDefend)
            ->with('recentGame', $player->recentGame())
            ->with('recentGameData', $recentGameData)
            ->with('player', $player);
    }
}

resources/views/Players/createOrUpdate.blade.php
@extends('layouts.app')
@section('content')
    @if(isset($player))
        {{ Form::model($player, ['route' => ['player.update', $player->id], 'method' => 'put']) }}
        {{ Form::hidden('id', $player->id) }}
        @if (session ('error'))
            <div style="display: flex" class="alert alert-danger">
                <strong class="text-center">{{ session('error') }}</strong>
                <div style="display: flex; justify-content: right">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                </div>
            </div>
        @endif
    @else
        {{ Form::open(['route' => 'player.store', 'method' => 'post']) }}
        @if (session ('error'))
            <div style="display: flex" class="alert alert-danger">
                <strong class="text-center">{{ session('error') }}</strong>
                <div style="display: flex; justify-content: right">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                </div>
            </div>
        @endif
    @endif
            {{ Form::label('firstname', 'Voornaam')}}
            {{ Form::text('firstname', Request::old('firstname')) }}
            @error('firstname')
                <div class="alert alert-danger">{{$message}}</div>
            @enderror
            {{ Form::label('surname', 'Achternaam')}}
            {{ Form::text('surname', Request::old('surname')) }}
            @error('surname')
                <div class="alert alert-danger">{{$message}}</div>
            @enderror
            {{ Form::label('date_of_birth', 'Geboortedatum')}}
            {{ Form::date('date_of_birth', Request::old('date_of_birth')) }}
            @error('date_of_birth')
                <div class="alert alert-danger">{{$message}}</div>
            @enderror
            {{ Form::submit('Opslaan', ['class'=>'btn btn-primary', 'id' => 'save_button']) }}
        {{ Form::close() }}
@endsection

resources/views/Players/index.blade.php
@extends('layouts.app')
@section('content')
    <div>
        @if (session('success'))
            <div style="display: flex" class="alert alert-success">
                <strong class="text-center">{{ session('success') }}</strong>
                <div style="display: flex; justify-content: right">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                </div>
            </div>
        @endif
        <div style="padding-left: 3.5rem; height: 70px">
            <a href="{{ route('player.create') }}" ; class="btn btn-success btn-lg shadow-sm">Nieuwe speler</a>
        </div>
        <div class="container">
            <div class="row">
                <div class="col col-lg-2 font-weight-bold">Naam</div>
                <div class="col col-lg-2 font-weight-bold">Geboortedatum</div>
            </div>
            @foreach($players as $player)
                <div class="row">
                    <div class="col col-lg-2"> <a href="{{ route('player.show', $player->id) }}">{{ $player->fullname }}</a></div>
                    <div class="col col-lg-2">{{ $player->date_of_birth }}</div>
                    <div class="col">
                        <div class="row">
                            <a class="btn btn-outline-info" href="{{ route('player.displayStatistics', $player->id) }}">Info</a>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
@endsection

resources/views/Players/show.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-md-center">
        <div class="h1">{{ $playerData['fullname'] }}</div>
    </div>
    <div class="row">
        <ul class="list-group">
            <li class="list-group-item">Geboortedatum: {{ $playerData['dateOfBirth'] }}</li>
            <li class="list-group-item">Aangemaakt: {{ $playerData['dateOfCreation'] }}</li>
        </ul>
    </div>
    <div class="row">
        <a class="btn btn-outline-secondary" href="{{ route('player.edit', $player->id) }}">Bewerken</a>
        {{ Form::open(['route'=> ['player.destroy', $player->id], 'onsubmit'=> "return confirm('Weet je het zeker?')", 'method'=>'POST']) }}
        {{ method_field('DELETE') }}
        {{ Form::submit('Verwijderen', ['class'=>'btn btn-outline-danger', 'id' => 'delete_button']) }}
        {{ Form::close() }}
    </div>
</div>
@endsection

resources/views/Players/statistics.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="h1 row justify-content-md-center">
        {{ $player->fullname }}
    </div>
    <div class="row justify-content-md-center">
        <div class="row justify-content-md-center">
            <div class="row justify-content-md-center">
                @isset($recentGame)
                <div class="h2">Recente wedstrijd</div>
                <div class="col; h6">{{ $recentGameData['recentGameDuration'] }}</div>
                <div class="row justify-content-md-center">
                    <div class="col; h5">
                        <div class="row">A: {{ $recentGame->teamOneAttackPlayerOneId->fullname ?? 'Niet gevonden'}}</div>
                        <div class="row">V: {{ $recentGame->teamOneDefendPlayerTwoId->fullname ?? 'Niet gevonden'}}</div>
                    </div>
                    <div class="col col-lg-2; h2">{{ $recentGameData['score'] }}</div>
                    <div class="col; h5">
                        <div class="row">A: {{ $recentGame->teamTwoAttackPlayerThreeId->fullname ?? 'Niet gevonden'}}</div>
                        <div class="row">V: {{ $recentGame->teamTwoDefendPlayerFourId->fullname ?? 'Niet gevonden'}}</div>
                    </div>
                    <div class="col; h6">{{ $recentGameData['recentGameDate'] }}  </div>
                </div>
                @endisset
            </div>
            <div class="col">
                <div class="h3 row justify-content-md-center">Totaal</div>
                <div class="card" style="width: 14rem;">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">Wedstrijden: {{ $playerStatsTotal['playerGamesTotal'] ?? '0' }}</li>
                        <li class="list-group-item">Goals: {{ $playerStatsTotal['playerGoalsTotal'] ?? '0' }}</li>
                        <li class="list-group-item">Eigen goals: {{ $playerStatsTotal['playerOwnGoalsTotal'] ?? '0' }}</li>
                        <li class="list-group-item">Middenveld goals: {{ $playerStatsTotal['playerMidfieldGoalsTotal'] ?? '0' }}</li>
                        <li class="list-group-item">Gem goals per wedstrijd: {{ $playerStatsTotal['avgGoalsPerGameTotal'] }}</li>
                        <li class="list-group-item">Gem eigen goals per wedstrijd: {{ $playerStatsTotal['avgOwnGoalsPerGameTotal'] }}</li>
                        <li class="list-group-item">Gem middenveld goals per wedstrijd: {{ $playerStatsTotal['avgMidfieldGoalsPerGameTotal'] }}</li>
                        <li class="list-group-item">Win percentage: {{ $playerStatsTotal['winPercentageTotal'] ?? '0' }}%</li>
                        <li class="list-group-item">Komt voor: {{ $playerStatsTotal['gameAppearanceTotal'] ?? '0' }}%</li>
                    </ul>
                </div>
                <div class="h3 row justify-content-md-center">Aanval</div>
                <div class="card" style="width: 14rem;">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">Wedstrijden: {{ $playerStatsAttack['playerGamesAttack'] ?? '0' }}</li>
                        <li class="list-group-item">Goals: {{ $playerStatsAttack['playerGoalsAttack'] ?? '0' }}</li>
                        <li class="list-group-item">Eigen goals: {{ $playerStatsAttack['playerOwnGoalsAttack'] ?? '0' }}</li>
                        <li class="list-group-item">Middenveld goals: {{ $playerStatsAttack['playerMidfieldGoalsAttack'] ?? '0' }}</li>
                        <li class="list-group-item">Gem goals per wedstrijd: {{ $playerStatsAttack['avgGoalsPerGameAttack'] }}</li>
                        <li class="list-group-item">Gem eigen goals per wedstrijd: {{ $playerStatsAttack['avgOwnGoalsPerGameAttack'] }}</li>
                        <li class="list-group-item">Gem middenveld goals per wedstrijd: {{ $playerStatsAttack['avgMidfieldGoalsPerGameAttack'] }}</li>
                        <li class="list-group-item">Win percentage: {{ $playerStatsAttack['winPercentageAttack'] ?? '0' }}%</li>
                        <li class="list-group-item">Komt voor: {{ $playerStatsAttack['gameAppearanceAttack'] ?? '0' }}%</li>
                    </ul>
                </div>
                <div class="h3 row justify-content-md-center">Verdediging</div>
                <div class="card" style="width: 14rem;">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">Wedstrijden: {{ $playerStatsDefend['playerGamesDefend'] ?? '0' }}</li>
                        <li class="list-group-item">Goals: {{ $playerStatsDefend['playerGoalsDefend'] ?? '0' }}</li>
                        <li class="list-group-item">Eigen goals: {{ $playerStatsDefend['playerOwnGoalsDefend'] ?? '0' }}</li>
                        <li class="list-group-item">Gem goals per wedstrijd: {{ $playerStatsDefend['avgGoalsPerGameDefend'] ?? '0' }}</li>
                        <li class="list-group-item">Gem eigen goals per wedstrijd: {{ $playerStatsDefend['avgOwnGoalsPerGameDefend'] ?? '0' }}</li>
                        <li class="list-group-item">Win percentage: {{ $playerStatsDefend['winPercentageDefend'] ?? '0' }}%</li>
                        <li class="list-group-item">Komt voor: {{ $playerStatsDefend['gameAppearanceDefend'] ?? '0'}}%</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection